version: "3.9"

services:
  main_server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - MAIN_SERVER_DATABASE_URL=${MAIN_SERVER_DATABASE_URL:-sqlite:////data/dev.db}
      - MAIN_SERVER_HOST=0.0.0.0
      - MAIN_SERVER_PORT=8080
    ports:
      - "${MAIN_SERVER_PORT}:8080"
    volumes:
      - ../data:/data
    restart: unless-stopped
